services:
  api:
    image: python:3.13-bookworm
    container_name: social_media_dashboard_api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash -c ". ./venv/bin/activate && pip install -r requirements.txt && python main.py"
    working_dir: /app
    hostname: api